### ISSUE TITLE
Some problem with numpy random generator call?

### ISSUE THREAD

**Issue by harmeling** [brett-daley/gym-classics#3]
First of all: THANK YOU for the really nice toolbox!

I have some issue with the following code:
```
import gym      # version 0.26.2
import gym_classics
env = gym.make('ClassicGridworld-v0')
state = env.reset()
env.step(1)
```
Running python (3.9, 3.10, 3.11) I get some error like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "/usr/local/lib/python3.9/site-packages/gym/wrappers/env_checker.py", line 37, in step
    return env_step_passive_checker(self.env, action)
  File "/usr/local/lib/python3.9/site-packages/gym/utils/passive_env_checker.py", line 214, in env_step_passive_checker
    result = env.step(action)
  File "/usr/local/lib/python3.9/site-packages/gym_classics/envs/abstract/base_env.py", line 67, in step
    elements = self._sample_random_elements(state, action)
  File "/usr/local/lib/python3.9/site-packages/gym_classics/envs/abstract/noisy_gridworld.py", line 14, in _sample_random_elements
    return [self._noisy_action(action)]
  File "/usr/local/lib/python3.9/site-packages/gym_classics/envs/abstract/noisy_gridworld.py", line 23, in _noisy_action
    p = self.np_random.rand()
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'rand'
```
I guess it can be easily solved by changing:
```
  File "/usr/local/lib/python3.9/site-packages/gym_classics/envs/abstract/noisy_gridworld.py", line 23, in _noisy_action
    p = self.np_random.rand()
```
to 
```
    p = self.np_random.random()
```

**Comment by brett-daley** [comment]
Newer versions of `numpy` have started using `Generator` instead of `RandomState`, and it looks like the APIs are slightly different. If you downgrade to `numpy 1.16` then I think it will work for now, but I'll update the code to start using `Generator` instead.

**Comment by harmeling** [comment]
Great!  Looking forward to it!  Thank you.
